#!/usr/bin/env node

/**
 * Generate env.js from Vercel environment variables
 * This script runs during Vercel build to inject environment variables
 */

const fs = require('fs');
const path = require('path');

// Get environment variables from Vercel
const API_URL = process.env.API_URL || 'https://gestion-compras-ch.onrender.com/api';
const APP_NAME = process.env.APP_NAME || 'Sistema de Compras Cielito Home';
const APP_VERSION = process.env.APP_VERSION || '1.0.0';

// Generate env.js content
const envContent = `// Auto-generated environment configuration
// Generated at build time from Vercel environment variables
// DO NOT EDIT THIS FILE MANUALLY

const ENV_CONFIG = {
  API_URL: '${API_URL}',
  APP_NAME: '${APP_NAME}',
  APP_VERSION: '${APP_VERSION}',
  ENVIRONMENT: 'production',
  BUILD_TIME: '${new Date().toISOString()}'
};

console.log('🚀 Production environment loaded:', ENV_CONFIG.ENVIRONMENT);

// Make available globally
window.ENV = ENV_CONFIG;

// Export for modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ENV_CONFIG;
}
`;

// Write to js/env.js
const outputPath = path.join(__dirname, 'js', 'env.js');
fs.writeFileSync(outputPath, envContent, 'utf8');

console.log('✅ Environment file generated successfully!');
console.log('   API_URL:', API_URL);
console.log('   Output:', outputPath);
